### ISSUE TITLE
怎么给electron设置整个应用的sock5代理认证

### ISSUE THREAD

**Issue by 600888** [MissGwen/MissGwen#1]
我使用了electron-session-proxy模块，代理好像没有生效
```
    const url = `${proxyType}://${username}:${password}@${remoteAddress}:${remotePort}`;
    const proxyRules = await sockProxyRules(url);

    // 为默认会话设置代理
    session.defaultSession.setProxy({ proxyRules }, (error) => {
        if (error) {
            console.error('Failed to set proxy:', error);
        } else {
            console.log('Proxy set successfully');
        }
    });
```

**Comment by MissGwen** [comment]
`session.defaultSession.setProxy`  目前最新版本返回 `Promise<void>` ，现在使用 回调 处理 好像会报错
这个 `electron-session-proxy` 模块目前只支持 socks4/5 的代理验证转发，
其次保证 socks代理地址是可用的，再看一下控制台有没有报错，可以发一下
如果方便，可以给我提供一个最小的复现单元，我本地跑一下试试 🥰🥰

ps：我也不是大佬，尽力帮你解决

> 我使用了electron-session-proxy模块，代理好像没有生效
> 
> ```
>     const url = `${proxyType}://${username}:${password}@${remoteAddress}:${remotePort}`;
>     const proxyRules = await sockProxyRules(url);
> 
>     // 为默认会话设置代理
>     session.defaultSession.setProxy({ proxyRules }, (error) => {
>         if (error) {
>             console.error('Failed to set proxy:', error);
>         } else {
>             console.log('Proxy set successfully');
>         }
>     });
> ```

**Comment by MissGwen** [comment]
> 我使用了electron-session-proxy模块，代理好像没有生效
> 
> ```
>     const url = `${proxyType}://${username}:${password}@${remoteAddress}:${remotePort}`;
>     const proxyRules = await sockProxyRules(url);
> 
>     // 为默认会话设置代理
>     session.defaultSession.setProxy({ proxyRules }, (error) => {
>         if (error) {
>             console.error('Failed to set proxy:', error);
>         } else {
>             console.log('Proxy set successfully');
>         }
>     });
> ```

`session.defaultSession.setProxy` 目前最新版本返回 `Promise<void>` ，现在使用 回调 处理 好像会报错
`electron-session-proxy` 这个模块目前只支持 socks4/5 的代理验证转发，
其次保证 socks 代理地址是可用的，再看一下控制台有没有报错，可以发一下
如果方便，可以给我提供一个最小的复现单元，我本地跑一下试试 🥰🥰

ps：我也不是大佬，尽力帮你解决

**Comment by 600888** [comment]
我简单讲一下我的需求吧，各个工控机(可以认为是电脑)上和云服务器上安装了自己的搭建的VPN，他们之间可以互相访问。本来只要给客户安装VPN，他直接打开网页其实就可以满足需求了。但因为VPN安装、配置比较繁琐，领导想让我在云端再部署一台socks5服务器，需要用户名和密码认证，再做一个远程登录客户端，配置socks5客户端代理。这样客户安装了客户端就可以直接访问各台工控机上的web网站了。描述起来差不多就是下面这张图片
![1](https://github.com/user-attachments/assets/8c0c50d8-ab9e-4b10-9998-1456ea68cdc1)
**我在elctron里面通过webview加载网页**
![2](https://github.com/user-attachments/assets/09a5d1be-1b17-4068-8cba-650196352f4c)

**electron主进程代码**

const { app, BrowserWindow, session } = require('electron');
import { sockProxyRules } from "electron-session-proxy";

const path = require('path');

async function setProxy() {
    const proxyType = 'socks5';
    const username = 'username';
    const password = 'password';
    const remoteAddress = '127.0.0.1';   // 实际使用的是远端地址
    const remotePort = 1080;

    const url = `${proxyType}://${username}:${password}@${remoteAddress}:${remotePort}`;
    const proxyRules = await sockProxyRules(url);

    // 不使用socks5认证可以成功连上
    // proxyRules = `${proxyType}://${remoteAddress}:${remotePort}`;

    console.log(proxyRules);

    // 为默认会话设置代理
    session.defaultSession.setProxy({ proxyRules }, (error) => {
        if (error) {
            console.error('Failed to set proxy:', error);
        } else {
            console.log('Proxy set successfully');
        }
    });
}

function createWindow() {
    const mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            webviewTag: true
        }
    });

    mainWindow.loadURL("index.html");
}

app.on('ready', async () => {
    await setProxy();
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});
![3](https://github.com/user-attachments/assets/f58d6222-b57b-47fe-931c-ee0a9d697aff)

**Comment by MissGwen** [comment]
> 我简单讲一下我的需求吧，各个工控机(可以认为是电脑)上和云服务器上安装了自己的搭建的VPN，他们之间可以互相访问。本来只要给客户安装VPN，他直接打开网页其实就可以满足需求了。但因为VPN安装、配置比较繁琐，领导想让我在云端再部署一台socks5服务器，需要用户名和密码认证，再做一个远程登录客户端，配置socks5客户端代理。这样客户安装了客户端就可以直接访问各台工控机上的web网站了。描述起来差不多就是下面这张图片 ![1](https://private-user-images.githubusercontent.com/59718553/398422351-8c0c50d8-ab9e-4b10-9998-1456ea68cdc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjAwMzQsIm5iZiI6MTczNTExOTczNCwicGF0aCI6Ii81OTcxODU1My8zOTg0MjIzNTEtOGMwYzUwZDgtYWI5ZS00YjEwLTk5OTgtMTQ1NmVhNjhjZGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzRiOTdlOWIzZGEzNDE2ZmRhMDM3NGY1YjMxMTdhNzYxZDJlNzliZWY4OWQyMWY1MzJiNjc3YzVkNGNiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W9dtsvARoAeSvQoHnbE5G8aCjPco0ZZdfTyyNr6iWAA) **我在elctron里面通过webview加载网页** ![2](https://private-user-images.githubusercontent.com/59718553/398423468-09a5d1be-1b17-4068-8cba-650196352f4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjAwMzQsIm5iZiI6MTczNTExOTczNCwicGF0aCI6Ii81OTcxODU1My8zOTg0MjM0NjgtMDlhNWQxYmUtMWIxNy00MDY4LThjYmEtNjUwMTk2MzUyZjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YmUxNDE2ZTUyZDQ3YTMyZDcwNjI2MTUzZWNhY2Y3NmVjNGY4YmUzODZmMmQ5MzI1YmY5MzFhODQ2YzI3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KaERuAOpJGgK094f3hltTRsanFw0L4v3yA8MCtC5yvc)
> 
> **electron主进程代码**
> 
> const { app, BrowserWindow, session } = require('electron'); import { sockProxyRules } from "electron-session-proxy";
> 
> const path = require('path');
> 
> async function setProxy() { const proxyType = 'socks5'; const username = 'username'; const password = 'password'; const remoteAddress = '127.0.0.1'; // 实际使用的是远端地址 const remotePort = 1080;
> 
> ```
> const url = `${proxyType}://${username}:${password}@${remoteAddress}:${remotePort}`;
> const proxyRules = await sockProxyRules(url);
> 
> // 不使用socks5认证可以成功连上
> // proxyRules = `${proxyType}://${remoteAddress}:${remotePort}`;
> 
> console.log(proxyRules);
> 
> // 为默认会话设置代理
> session.defaultSession.setProxy({ proxyRules }, (error) => {
>     if (error) {
>         console.error('Failed to set proxy:', error);
>     } else {
>         console.log('Proxy set successfully');
>     }
> });
> ```
> 
> }
> 
> function createWindow() { const mainWindow = new BrowserWindow({ width: 800, height: 600, webPreferences: { nodeIntegration: true, contextIsolation: false, webviewTag: true } });
> 
> ```
> mainWindow.loadURL("index.html");
> ```
> 
> }
> 
> app.on('ready', async () => { await setProxy(); });
> 
> app.on('window-all-closed', () => { if (process.platform !== 'darwin') { app.quit(); } });
> 
> app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) { createWindow(); } }); ![3](https://private-user-images.githubusercontent.com/59718553/398423708-f58d6222-b57b-47fe-931c-ee0a9d697aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjAwMzQsIm5iZiI6MTczNTExOTczNCwicGF0aCI6Ii81OTcxODU1My8zOTg0MjM3MDgtZjU4ZDYyMjItYjU3Yi00N2ZlLTkzMWMtZWUwYTlkNjk3YWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YjY1MDk3OWI2OWNjMTYyYmUyODE2MGFjNDVjOWQwYzJjNGQ3ZDhlNjg2NzJjMGU5M2VhMGMyOWYxNzg0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2QYleNJwD2OkjIWvIYg6lhmKu_hVz91BURmn01z4XSM)

如果使用的是 webview 进行目标地址的引入，我的建议是 👇
``` html
// 使用 `partition` 属性进行标注
<webview src="https://www.baidu.com" partition="persist:github"></webview>
``` 
参考连接 [https://www.electronjs.org/zh/docs/latest/api/webview-tag#partition](url)
然后 👇
``` ts
  const proxyRules = await sockProxyRules('socks5://u:p@127.0.0.1:1080')
  const ses = session.fromPartition('persist:github') // 与 webview 的 partition 值对应
  await ses.setProxy({ proxyRules })
```
今天测试过 使用 `session.defaultSession.setProxy` 进行设置代理，结果是不通的，依然使用的是本机的 IP

但是很抱歉的是，我看到您的目标地址是 `http` 协议的，目前这个包还不支持 `http` , 只能使用 `https` 协议的目标地址 😥😥😥，非常抱歉

**Comment by 600888** [comment]
谢谢你的答复，给我提供了一种思路，或许可以通过socks5本地转http代理的方式实现

**Comment by 600888** [comment]
谢谢你的答复，给我提供了一种思路，或许可以通过socks5本地转http代理的方式实现
